[project]
name = "scripts"
version = "0.1.0"
description = "A collection of scripts for organizing media files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow-heif>=1.2.0",
    "pyautogui",
]
